version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db-dev
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: main-menu
      PGDATA: /docker/pg
    volumes:
      - ./volumes/pg:/docker/pg
