// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using main_menu.Contexts;

#nullable disable

namespace main_menu.Migrations
{
	[DbContext(typeof(PgContext))]
	[Migration("20240701233122_CreateCategoryTable")]
	partial class CreateCategoryTable
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "8.0.6")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("main_menu.models.Category", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uuid");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.Property<int>("Order")
						.HasColumnType("integer");

					b.HasKey("Id");

					b.ToTable("Category");
				});

			modelBuilder.Entity("main_menu.models.User", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uuid");

					b.Property<string>("Email")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("Password")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("User");
				});
#pragma warning restore 612, 618
		}
	}
}
